# Buildpack API version
api = "0.2"

# Buildpack ID and metadata
[buildpack]
id = "io.dashaun.buildpacks.cobol"
version = "0.0.1"
name = "COBOL Buildpack"

# Preferred stack
[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

# Untested stack
[[stacks]]
id = "heroku-18"